version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "20:00"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/packages/mq-playground"
    schedule:
      interval: "daily"
      time: "20:00"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/packages/mq-web"
    schedule:
      interval: "daily"
      time: "20:00"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/editors/vscode"
    schedule:
      interval: "daily"
      time: "20:00"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "20:00"
    open-pull-requests-limit: 10
