id = "mq"
name = "mq"
description = "mq language support - jq-like tool for Markdown processing"
version = "0.1.0"
schema_version = 1
authors = [
  "Takahiro Sato <harehare1110@gmail.com>",
]
repository = "https://github.com/harehare/mq"

[grammars.mq]
repository = "https://github.com/harehare/tree-sitter-mq"
commit = "main"

[languages.mq]
name = "mq"
grammar = "mq"
path_suffixes = ["mq"]
line_comments = ["#"]
block_comment = [""]

[language_servers.mq-lsp]
name = "mq-lsp"
languages = ["mq"]
