[package]
categories.workspace = true
description = "Code formatter for mq query language"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "mq-formatter"
repository.workspace = true
version.workspace = true

[dependencies]
mq-lang = {workspace = true, features = ["cst"]}
rustc-hash.workspace = true

[dev-dependencies]
rstest.workspace = true
