[package]
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license-file.workspace = true
name = "mq-formatter"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
mq-lang = {workspace = true, features = ["cst"]}
rustc-hash.workspace = true

[dev-dependencies]
rstest.workspace = true
