[package]
categories.workspace = true
description = "Read-Eval-Print Loop (REPL) for mq query language"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "mq-repl"
repository.workspace = true
version.workspace = true

[dependencies]
arboard.workspace = true
colored.workspace = true
dirs.workspace = true
itertools.workspace = true
miette.workspace = true
mq-hir.workspace = true
mq-lang.workspace = true
mq-markdown.workspace = true
regex-lite.workspace = true
rustyline = {version = "17.0.2", default-features = false, features = ["custom-bindings", "with-file-history"]}
strum = {version = "0.27.2", features = ["derive"]}

[dev-dependencies]
mq-test.workspace = true
rstest.workspace = true
