[book]
authors = ["Takahiro Sato"]
description = "Reference on the mq."
language = "en"
src = "src"
title = "mq - jq like tool for markdown processing"

[output.html]
additional-css = ["theme/custom.css"]
additional-js = ["theme/highlight-mq.js"]
default-theme = "navy"
git-repository-url = "https://github.com/harehare/mq"
no-section-label = true
preferred-dark-theme = "navy"
site-url = "/book"
smart-punctuation = true
