[package]
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license-file.workspace = true
name = "mq-python"
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]
name = "mq"

[dependencies]
mq-lang.workspace = true
mq-markdown.workspace = true
pyo3 = {version = "0.27.1", features = ["extension-module", "abi3-py39"]}
